version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/go/pkg/mod
      - /app/bin
    ports:
      - '8080:8080'
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.50' # Limit CPU usage
          memory: '512M' # Limit memory usage
      restart_policy:
        condition: on-failure # Restart if the app crashes
    healthcheck:
      test:
        ['CMD-SHELL', 'curl -f http://localhost:8080/api/v1/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_NON_ROOT_USER}
      MYSQL_PASSWORD: ${DB_NON_ROOT_PASSWD}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
