// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: attendees.sql

package database

import (
	"context"
	"database/sql"
)

const createAttendee = `-- name: CreateAttendee :exec
INSERT INTO attendees (first_name, last_name, email, qr_code, company_name, title, table_no, role, attendence, event_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAttendeeParams struct {
	FirstName   string
	LastName    string
	Email       string
	QrCode      sql.NullString
	CompanyName sql.NullString
	Title       sql.NullString
	TableNo     sql.NullInt32
	Role        sql.NullString
	Attendence  NullAttendeesAttendence
	EventID     int32
}

func (q *Queries) CreateAttendee(ctx context.Context, arg CreateAttendeeParams) error {
	_, err := q.db.ExecContext(ctx, createAttendee,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.QrCode,
		arg.CompanyName,
		arg.Title,
		arg.TableNo,
		arg.Role,
		arg.Attendence,
		arg.EventID,
	)
	return err
}

const deleteAllAttendees = `-- name: DeleteAllAttendees :exec
DELETE FROM attendees
`

func (q *Queries) DeleteAllAttendees(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAttendees)
	return err
}

const deleteAttendeeByID = `-- name: DeleteAttendeeByID :exec
DELETE FROM attendees WHERE id = ?
`

func (q *Queries) DeleteAttendeeByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAttendeeByID, id)
	return err
}

const findAttendeeByEmail = `-- name: FindAttendeeByEmail :one
SELECT id, first_name, last_name, email, qr_code, company_name, title, table_no, role, attendence, event_id FROM attendees WHERE email = ?
`

func (q *Queries) FindAttendeeByEmail(ctx context.Context, email string) (Attendee, error) {
	row := q.db.QueryRowContext(ctx, findAttendeeByEmail, email)
	var i Attendee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.QrCode,
		&i.CompanyName,
		&i.Title,
		&i.TableNo,
		&i.Role,
		&i.Attendence,
		&i.EventID,
	)
	return i, err
}

const getAllAttendees = `-- name: GetAllAttendees :many
SELECT id, first_name, last_name, email, qr_code, company_name, title, table_no, role, attendence, event_id FROM attendees
`

func (q *Queries) GetAllAttendees(ctx context.Context) ([]Attendee, error) {
	rows, err := q.db.QueryContext(ctx, getAllAttendees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendee
	for rows.Next() {
		var i Attendee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.QrCode,
			&i.CompanyName,
			&i.Title,
			&i.TableNo,
			&i.Role,
			&i.Attendence,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAttendeesPaginated = `-- name: GetAllAttendeesPaginated :many
SELECT id, first_name, last_name, email, qr_code, company_name, title, table_no, role, attendence, event_id FROM attendees LIMIT ? OFFSET ?
`

type GetAllAttendeesPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllAttendeesPaginated(ctx context.Context, arg GetAllAttendeesPaginatedParams) ([]Attendee, error) {
	rows, err := q.db.QueryContext(ctx, getAllAttendeesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attendee
	for rows.Next() {
		var i Attendee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.QrCode,
			&i.CompanyName,
			&i.Title,
			&i.TableNo,
			&i.Role,
			&i.Attendence,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAttendeeWithQRCode = `-- name: SaveAttendeeWithQRCode :exec
UPDATE attendees SET qr_code = ? WHERE id = ?
`

type SaveAttendeeWithQRCodeParams struct {
	QrCode sql.NullString
	ID     int32
}

func (q *Queries) SaveAttendeeWithQRCode(ctx context.Context, arg SaveAttendeeWithQRCodeParams) error {
	_, err := q.db.ExecContext(ctx, saveAttendeeWithQRCode, arg.QrCode, arg.ID)
	return err
}
